apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: chickendev/my-k8s-site:v2   # ← 更新
        imagePullPolicy: Always                      # ← Never から変更
        ports:
        - containerPort: 80
        env:
        - name: SITE_TITLE
          valueFrom:
            configMapKeyRef:
              name: my-site-config
              key: SITE_TITLE
        - name: APP_ENV
          valueFrom:
            configMapKeyRef:
              name: my-site-config
              key: APP_ENV
        - name: API_KEY
          valueFrom:
            secretKeyRef:
              name: my-site-secret
              key: API_KEY